### ISSUE TITLE
Bitcoin is unethical

### ISSUE THREAD

**Issue by DC7IA** [SartoxOnlyGNU/audacium#33]
**Describe the bug**
Bitcoin is unethical and a bug which threatens the very existance of humanity as it harms the planet through global warming.

**To Reproduce**
1. start mining bitcoin
2. planet gets warm
3. planet dies

**Expected behavior**
Bitcoin should not be used for donations.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
You know, bitcoin is *really* bad.

I'm writing this jokingly, but I'm also serious. I think it's great to have a fork like this, but please do not endanger our planet. Quit bitcoin. :) 

Bitcoin consumes as much energy as whole countries, do you think risking a planet is worth some transactions?

https://www.bbc.com/news/technology-56012952

**Comment by AnErrupTion** [comment]
Bitcoin isn't destroying our planet. Sure, it consumes a lot of power, but pretty much all other crypto currencies do. So basically, ban crypto currencies everywhere and force people use the even more unethical PayPal? (I mean, there is a way to donate to me via PayPal, because it's extremely popular and a lot of people use it, pretty much like Bitcoin... but your point is still invalid. And if you say it consumes morer power than other crypto currencies, yes probably, because Bitcoin is mined much more than other ones.)

**Comment by DC7IA** [comment]
> So basically, ban crypto currencies everywhere

Sounds like a good idea, actually. But...

> Bitcoin isn't destroying our planet. Sure, it consumes a lot of power,

A ridiculous amount of power. The average transaction needs much more power than a VISA transaction: https://www.statista.com/statistics/881541/bitcoin-energy-consumption-transaction-comparison-visa/

A single Bitcoin transaction needs on average 1662.11 kWh, while a single VISA transaction needs on average 0.0014863 kWh

That is ~1.118 million times as much energy.

**Comment by AnErrupTion** [comment]
You know that it's electricity being used right? Then think about the other, much worse energy sources like nuclear. Do you think we should eradicate Bitcoin first or nuclear? Of course, the latter. And Bitcoin is like AI, either let it live along with us or pretty much destroy a part of the world. You can't change the fact that Bitcoin is in our lives, but you can change the fact that nuclear is, because it's already been replaced (and also other unrenewable energy sources too)

**Comment by MurdoMaclachlan** [comment]
Sorry, but that's a logical fallacy. To say "this thing is really bad, but this thing that's unrelated to the conversation is worse so I'll still use the bad thing" is pure nonsense.

And nuclear *is* unrelated to the conversation. The conversation is about what form of donations are best for the environment, which nuclear energy doesn't relate to. The energy used for a bitcoin transaction is just as likely to have been generated at a nuclear source as the energy used for a VISA transaction; what matters here is the amount.

It's also a logical fallacy to say "it's bad but lots of other people are using it, so we'll use it too". That's *exactly* the mindset that results in it still being used so much. Yes, you won't make much difference not using it, but if everyone takes that as a reason to keep using it, then *definitely* nothing will ever happen, and you will still bear some of the responsibility for the damage dealt to the planet.

**Comment by AnErrupTion** [comment]
I think we are going too off-topic here, closing.

**Comment by jeyemwey** [comment]
Please reopen, the original problem has not been solved yet.

**Comment by DC7IA** [comment]
> Do you think we should eradicate Bitcoin first or nuclear?

Oh, why not do both?



> You can't change the fact that Bitcoin is in our lives, but you can change the fact that nuclear is, because it's already been replaced

Oh, if it already has been replaced then we can actually do both!

Not using bitcoin is simple: simply by not using it

**Comment by mish1git** [comment]
We can pretty much fix cryptos fucking up the environment by moving all the big crypto farms from China to Paraguay.
